/**
 * @description Exception クラスは、例外オブジェクトを生成するためのクラスです。
 * メッセージは、生成されたオブジェクトの message プロパティに設定されます。
 */
class Exception {
	/**
	 * コンストラクタ
	 * @description スクリプト以外の要因で発生する例外オブジェクトはすべて Exception クラスのオブジェクトです ( たとえば 除算エラー例外など )。
	 * @param message 例外メッセージを渡します。
	 */
	function Exception( message:string );

	/**
	 * 例外の理由を表す文字列を表すプロパティです。
	 */
	property message;

	/**
	 * 例外が発生するまでに通過した関数などの情報が記録されています ( 人間が読むための文字列として記録されています )。
	 */
	property trace;
};
