markdown: kramdown
url: http://krkrz.github.io/multi_platform_design
highlighter: rouge
simple_search: http://google.com/search
kramdown:
  input: GFM
  syntax_highlighter: rouge
  extensions:
    - autolink
gems:
    - jemoji
    - jekyll-mentions
    - jekyll-sitemap
    - jekyll-feed
