name: CI
on:
  push:
    paths:
      - "**.tjs"
      - "**.md"
  pull_request:
      - "**.tjs"
      - "**.md"

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install dependencies
      - run: |
          sudo apt-get update
          sudo apt-get install mono-complete perl

      - name: Build API reference
      - run: |
          cd classes
          perl tjs2.pl
          cd ..

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: docs
          clean: true
          single-commit: true
